name: Release Drafter
on:
  push:
    branches:
      - main

permissions:
  security-events: read
  contents: write
  actions: read
  
jobs:
   update_release_draft:
      uses: jetty-project/.github/.github/workflows/release-drafter.yml@master
